```{r vectors}
john_vector1<-c("John","M","05/04/1947",55,45,56,87,90)
suresh_vector2<-c("suresh","M","09/12/1997",56,78,98,56,100)
names(john_vector1)<-c("Name","Gender","DOB","Maths","Physics","Chemistry","English","Biology")
bhavani_vector3<-c("Bhavani","F","01/08/1996",90,89,91,95,100)
john_vector1
suresh_vector2
bhavani_vector3
print("******************concatination***********************************************")

#combining two vectors
c(john_vector1,bhavani_vector3)
print("***************details*************************************************")

#Displaying Name,Gender and DOB details
john_vector1[1:3]
bhavani_vector3[1:3]
suresh_vector2[1:3]
print("*******************Conversions***********************************************")
#converting string to numeric
#total marks in biology
total_Bilolgy<-as.numeric(john_vector1[8])+as.numeric(suresh_vector2[8])+as.numeric(bhavani_vector3[8])
print("total Biology marks")

total_Bilolgy

```

```{r Sequence Numbers}
x<-1:20
x
count1<-c(2,45,seq(2:10))
count1
count2<-c(143,seq(from=23,to=99,by=10))
count2
students<-c("A","B","C","D","E","F")
students
#even num between  0 to 100
Numbers<-seq(0,100,by=2)
Numbers
#adding of 2 seq of vectors
a<-c(1:10)
b<-c(11:20)
a+b
#length of seq
length(b)
#using se.int
int<-c(seq.int(2,20,length.out = 5))
int


```





```{r Matrices and Dataframe}
a<-c(10,20,30,40)
b<-c("bhavani","lakshmi","falthu","Donga")
x<-c(TRUE,FALSE,TRUE,FALSE)
df<-data.frame(a,b,x)
df
player_id<-c(5,2,11,42,25)
player<-c("pilakouta","carter","killian","johnston","filer")
 Min<-c(27,26,23,19,21)
 FG<-c(4,5,1,2,3)
 REB<-c(9,4,1,3,7)
date<-as.Date(c("2012-01-01","2014-12-01","2020-01-06","2007-12-09","2001-07-23"))
scores.data<-data.frame(player_id,player,Min,FG,REB,date)
scores.data
#retrieving specific data
player1<-data.frame(scores.data$player_id,scores.data$player,scores.data$date)
player1

#matrix
A=matrix(c(1,2,3,4,5,6),
nrows<-2,
ncolumn<-3,
byrow <-TRUE)
A
names<-matrix(c("bhavani","venkata"
  ,"bharath","priya","tommy","choclate"),
  nrows<-2,
  ncolumn<-3,
  byrow<-FALSE
  )
names
```


```{r subsetting }
c<-c(11,2,3,4,5,5.5,6.9,8.0)
#displying subset of vector
c[3]:c[7]
#duplicating indexex
c[c(1,1,1)]
#skipping of integers
x<-c(56,89,70,80,100)
x[-1]
L<-c(TRUE,FALSE,TRUE,FALSE,TRUE)
x[L]
c[which(x>5)]


```


```{r missing values}
Names<-c("Bhavana","Bow-Bow","Choclate","cutie")
sex<-c("F",NA,NA,NA)
Age<-c(22,NA,NA,NA)
toy<-c("nope","Bow-Bow","Choclate","cutie")
me<-data.frame(Names,sex,Age,toy)
me
na.omit(me)
is.na(sex)
na.omit(Age)
sum(is.na(me))
mean(is.na(me))


```

